aviation/airport/urls.py
from . import views
from django.urls import path

app_name = 'airport'

urlpatterns = [
    path('',views.index,name='index'),
    path('airport/',views.airport,name='airport'),
    path('airport/<int:airport_id>/',views.detail,name='detail'),

    #add airport
    path('add',views.create_airport,name='create_airport'),

    #edit
    path('update/<int:airport_id>/',views.update_airport,name="update_airport"),

    #delete
    path('delete/<int:airport_id>/',views.delete_airport,name='delete_airport'),

    #asia
    path('airport/asia',views.asia,name='asia'),

    #africa
    path('airport/africa',views.africa,name='africa'),

    #oceania
    path('airport/oceania',views.oceania,name='oceania'),

    #south and central america
    path('airport/southamerica',views.southandcentralamerica,name='southamerica'),

    #antartica
    path('airport/antartica',views.antartica,name='antartica'),

    #north america
    path('airport/northamerica',views.northamerica,name='northamerica'),
]

aviation/aviation/urls.py
from django.contrib import admin
from django.urls import include,path
from rest_framework import routers
from airport.views import AirportViewSet,LargeAirportsViewSet,MediumAirportsViewSet,SmallAirportsViewSet,HeliportsViewSet,SeaplaneBasesViewSet,AsiaViewSet,AfricaViewSet,OceaniaViewSet,SouthCentralAmericaViewSet,EuropeViewSet,NorthAmericaViewSet

router = routers.SimpleRouter()

# routers for airport types
router.register('api',AirportViewSet)
router.register('large',LargeAirportsViewSet)
router.register('medium',MediumAirportsViewSet)
router.register('small',SmallAirportsViewSet)
router.register('heliports',HeliportsViewSet)
router.register('seaplane',SeaplaneBasesViewSet)

# routers for continents
router.register('asia',AsiaViewSet)
router.register('africa',AfricaViewSet)
router.register('oceania',OceaniaViewSet)
router.register('southcentralameria',SouthCentralAmericaViewSet)
router.register('europe',EuropeViewSet)
router.register('northamerica',NorthAmericaViewSet)


urlpatterns = [
    path('',include(router.urls)),
    path('admin/', admin.site.urls),
    path('',include('airport.urls')),
]

aviation/airport/models.py
from django.db import models

# Create your models here.

class Airport (models.Model):
    def __str__(self):
        return self.airport_name

    # variables for airport types
    LARGE = "LARGE"
    MEDIUM = "MEDIUM"
    SMALL = "SMALL"
    SEAPLANE = "SEAPLANE"
    HELIPORT = "HELIPORT"

    AIRPORT_TYPES = [
        (LARGE, "large airport"),
        (MEDIUM, "medium airport"),
        (SMALL, "small airport"),
        (SEAPLANE, "seaplane base"),
        (HELIPORT, "heliport"),
    ]

    # variables for continents
    ASIA = "ASIA"
    SOUTH_AND_CENTRAL_AMERICA = "SOUTH_AND_CENTRAL_AMERICA"
    OCEANIA = "OCEANIA"
    AFRICA = "AFRICA"
    EUROPE = "EUROPE"
    NORTH_AMERICA = "NORTH_AMERICA"
    ANTARTICA = "ANTARTICA"

    CONTINENTS = [
        (ASIA, "Asia"),
        (SOUTH_AND_CENTRAL_AMERICA, "South and Central America"),
        (OCEANIA, "Oceania"),
        (AFRICA, "Africa"),
        (EUROPE, "Europe"),
        (NORTH_AMERICA, "North America"),
        (ANTARTICA, "Antartica"),
    ]

    airport_id = models.IntegerField(("id of airport"), null=False, blank=False, primary_key=True)
    airport_name = models.CharField(("name of airport"),max_length=100, null=False, blank=False)
    airport_type = models.CharField(("type of airport"),max_length=25,choices=AIRPORT_TYPES)
    latitude = models.FloatField("latitude degree")
    longitude = models.FloatField("longitude degree")
    elevation = models.IntegerField("elevation", null=True, blank=True)
    continent = models.CharField(("continent"),max_length=40,choices=CONTINENTS)
    country = models.CharField(("country"),max_length=100)
    municipality = models.CharField(("municipality"),max_length=100, null=True, blank=True)
    

    class Meta:
        ordering = ['airport_id', 'airport_name', 'airport_type', 'latitude', 'longitude','elevation','continent','country','municipality']

aviation/airport/forms.py
from django import forms
from .models import Airport

class AirportForm(forms.ModelForm):
    class Meta:
        model = Airport
        fields = ['airport_id','airport_name','airport_type','latitude','longitude','elevation','continent','country','municipality']
        # Defines the fields to be included in the form

aviation/airport/views.py
# Import modules

from django.shortcuts import render,redirect
from rest_framework import viewsets,filters
from rest_framework.pagination import PageNumberPagination
from .serializers import AirportSerializer
from .models import Airport
from .forms import AirportForm
from django.core.paginator import Paginator,EmptyPage, PageNotAnInteger



#################################################################
############################ Classes ############################
#################################################################

class AirportPagination(PageNumberPagination):
    page_size = 10
    page_size_query_param = 'page_size'
    max_page_size = 100

class AirportViewSet(viewsets.ModelViewSet):
    queryset = Airport.objects.all()
    serializer_class = AirportSerializer
    pagination_class = AirportPagination
    filter_backends = [filters.SearchFilter]
    search_fields = ['airport_name', 'country', 'airport_type', 'continent']


################# Classes for airport types #################

class LargeAirportsViewSet(viewsets.ModelViewSet):
    queryset = Airport.objects.filter(airport_type='large airport')
    serializer_class = AirportSerializer

class MediumAirportsViewSet(viewsets.ModelViewSet):
    queryset = Airport.objects.filter(airport_type='medium airport')
    serializer_class = AirportSerializer

class SmallAirportsViewSet(viewsets.ModelViewSet):
    queryset = Airport.objects.filter(airport_type='small airport')
    serializer_class = AirportSerializer

class HeliportsViewSet(viewsets.ModelViewSet):
    queryset = Airport.objects.filter(airport_type='heliport')
    serializer_class = AirportSerializer

class SeaplaneBasesViewSet(viewsets.ModelViewSet):
    queryset = Airport.objects.filter(airport_type='seaplane base')
    serializer_class = AirportSerializer


################# Classes for continents #################

class AsiaViewSet(viewsets.ModelViewSet):
    queryset = Airport.objects.filter(continent='Asia')
    serializer_class = AirportSerializer

class AfricaViewSet(viewsets.ModelViewSet):
    queryset = Airport.objects.filter(continent='Africa')
    serializer_class = AirportSerializer

class OceaniaViewSet(viewsets.ModelViewSet):
    queryset = Airport.objects.filter(continent='Oceania')
    serializer_class = AirportSerializer

class SouthCentralAmericaViewSet(viewsets.ModelViewSet):
    queryset = Airport.objects.filter(continent='South and Central America')
    serializer_class = AirportSerializer

class EuropeViewSet(viewsets.ModelViewSet):
    queryset = Airport.objects.filter(continent='Europe')
    serializer_class = AirportSerializer

class NorthAmericaViewSet(viewsets.ModelViewSet):
    queryset = Airport.objects.filter(continent='NorthAmerica')
    serializer_class = AirportSerializer



#################################################################
###################### CRUD Functionality  ######################
#################################################################


# CREATE: Renders a form to create a new airport entry
def create_airport(request):
    form = AirportForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('airport:index')
    
    return render(request,'airport/airport-form.html',{'form':form})


# READ: Renders the index and detail pages 
def index(request):
    return render(request,'airport/index.html')

def detail(request,airport_id):
    airport = Airport.objects.get(pk=airport_id)
    context = {
        'airport':airport,
    }
    return render(request,'airport/detail.html',context)


# UPDATE: Renders a form to update an existing airport entry
def update_airport(request,airport_id):
    airport = Airport.objects.get(airport_id=airport_id)
    form = AirportForm(request.POST or None, instance = airport)

    if form.is_valid():
        form.save()
        return redirect('airport:index')
    
    return render(request,'airport/airport-form.html',{'form':form, 'airport':airport})


# DELETE: Deletes an existing airport entry
def delete_airport(request,airport_id):
    airport = Airport.objects.get(airport_id=airport_id)

    if request.method == 'POST':
        airport.delete()
        return redirect('airport:airport')
    
    return render(request,'airport/airport-delete.html',{'airport':airport})



#################################################################
###################### View functions for  ######################
#################################################################

# Define view function for all airports
def airport(request):
    # Retrieve Airport objects
    airport_list = Airport.objects.all()
    
    # Get the value of 'airport_name' from request's GET parameters
    airport_name = request.GET.get('airport_name')
    
    # Check if 'airport_name' is not empty and is not None, then filter airport_list
    if airport_name != '' and airport_name is not None:
        airport_list = airport_list.filter(airport_name__icontains=airport_name)

    # Paginate the filtered airport_list, showing 10 airports per page
    paginator = Paginator(airport_list, 10)
    page = request.GET.get('page')
    
    try:
        # Try to retrieve the requested page of airports
        airports = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, show the first page
        airports = paginator.page(1)
    except EmptyPage:
        # If page is out of range, deliver the last page of results
        airports = paginator.page(paginator.num_pages)

    # Pass the paginated airports to the template    
    context = {
        'airport_list': airports,
    }
    # Render the 'airport.html' template with the context data
    return render(request,'airport/airport.html',context)


# Define view function for Asia airports
def asia(request):
    # Retrieve Airport objects filtered by continent
    airport_list = Airport.objects.filter(continent="Asia")
    
    # Get the value of 'airport_name' from request's GET parameters
    airport_name = request.GET.get('airport_name')
    
    # Check if 'airport_name' is not empty and is not None, then filter airport_list
    if airport_name != '' and airport_name is not None:
        airport_list = airport_list.filter(airport_name__icontains=airport_name)

    # Paginate the filtered airport_list, showing 10 airports per page
    paginator = Paginator(airport_list, 10)
    page = request.GET.get('page')
    
    try:
        # Try to retrieve the requested page of airports
        airports = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, show the first page
        airports = paginator.page(1)
    except EmptyPage:
        # If page is out of range, deliver the last page of results
        airports = paginator.page(paginator.num_pages)

    # Pass the paginated airports to the template    
    airport_asia = {
        'airport_list': airports,
    }
    # Render the 'asia.html' template with the context data
    return render(request,'airport/asia.html',airport_asia)


# Define view function for Africa airports
def africa(request):
    # Retrieve Airport objects filtered by continent
    airport_list = Airport.objects.filter(continent="Africa")
    
    # Get the value of 'airport_name' from request's GET parameters
    airport_name = request.GET.get('airport_name')
    
    # Check if 'airport_name' is not empty and is not None, then filter airport_list
    if airport_name != '' and airport_name is not None:
        airport_list = airport_list.filter(airport_name__icontains=airport_name)

    # Paginate the filtered airport_list, showing 10 airports per page
    paginator = Paginator(airport_list, 10)
    page = request.GET.get('page')
    
    try:
        # Try to retrieve the requested page of airports
        airports = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, show the first page
        airports = paginator.page(1)
    except EmptyPage:
        # If page is out of range, deliver the last page of results
        airports = paginator.page(paginator.num_pages)

    # Pass the paginated airports to the template    
    airport_africa = {
        'airport_list': airports,
    }
    # Render the 'africa.html' template with the context data
    return render(request,'airport/africa.html',airport_africa)


# Define view function for Oceania airports
def oceania(request):
    # Retrieve Airport objects filtered by continent
    airport_list = Airport.objects.filter(continent="Oceania")
    
    # Get the value of 'airport_name' from request's GET parameters
    airport_name = request.GET.get('airport_name')
    
    # Check if 'airport_name' is not empty and is not None, then filter airport_list
    if airport_name != '' and airport_name is not None:
        airport_list = airport_list.filter(airport_name__icontains=airport_name)

    # Paginate the filtered airport_list, showing 10 airports per page
    paginator = Paginator(airport_list, 10)
    page = request.GET.get('page')
    
    try:
        # Try to retrieve the requested page of airports
        airports = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, show the first page
        airports = paginator.page(1)
    except EmptyPage:
        # If page is out of range, deliver the last page of results
        airports = paginator.page(paginator.num_pages)

    # Pass the paginated airports to the template    
    airport_oceania = {
        'airport_list': airports,
    }
    # Render the 'oceania.html' template with the context data
    return render(request,'airport/oceania.html',airport_oceania)


# Define view function for South and Central America airports
def southandcentralamerica(request):
    # Retrieve Airport objects filtered by continent
    airport_list = Airport.objects.filter(continent="South and Central America")
    
    # Get the value of 'airport_name' from request's GET parameters

aviation/airport/templates/airport/africa.html
{% extends 'airport/base.html' %}

{% block body %}
    <h1>List of all airports in Africa</h1>

    <form action="" method="GET">
        <input type="search" name="airport_name">
        <button type="submit">Search</button>
    </form>

    {% for item in airport_list %}
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-4">
                <h4>{{ item.airport_name }}</h3>
                <h6>{{ item.municipality }}</h3>
                <h6>{{ item.country }}</h3>
            </div>
            <div class="col-md-2">
                <a href="{% url 'airport:detail'  item.airport_id %}" class="btn btn-success">Details</a>
            </div>
        </div>
    {% endfor %}

    <div class="pagination">
        <span class="step-links">
            {% if airport_list.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ airport_list.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ airport_list.number }} of {{ airport_list.paginator.num_pages }}.
            </span>

            {% if airport_list.has_next %}
                <a href="?page={{ airport_list.next_page_number }}">next</a>
                <a href="?page={{ airport_list.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

aviation/airport/templates/airport/airport-delete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ airport.airport_name }}?</h2>
    <button type="submit">Confirm</button>
    <button type="submit">Cancel</button>
</form>

aviation/airport/templates/airport/airport-form.html
{% extends 'airport/base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Save</button>
</form>
{% endblock %}

aviation/airport/templates/airport/airport.html
{% extends 'airport/base.html' %}

{% block body %}
<h1>List of all airports in the world</h1>

<form action="" method="GET">
    <input type="search" name="airport_name">
    <button type="submit">Search</button>
</form>

{% for item in airport_list %}
    <div class="row">
        <div class="col-md-3">
        </div>
        <div class="col-md-4">
            <h4>{{ item.airport_name }}</h3>
            <h6>{{ item.municipality }}</h3>
            <h6>{{ item.country }}</h3>
        </div>
        <div class="col-md-2">
            <a href="{% url 'airport:detail' item.airport_id %}" class="btn btn-success">Details</a>
        </div>
    </div>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if airport_list.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ airport_list.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ airport_list.number }} of {{ airport_list.paginator.num_pages }}.
        </span>

        {% if airport_list.has_next %}
            <a href="?page={{ airport_list.next_page_number }}">next</a>
            <a href="?page={{ airport_list.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>


{% endblock %}

aviation/airport/templates/airport/antartica.html
{% extends 'airport/base.html' %}

{% block body %}
    <h1>List of all airports in Antartica</h1>

    <form action="" method="GET">
        <input type="search" name="airport_name">
        <button type="submit">Search</button>
    </form>

    {% for item in airport_list %}
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-4">
                <h4>{{ item.airport_name }}</h3>
                <h6>{{ item.municipality }}</h3>
                <h6>{{ item.country }}</h3>
            </div>
            <div class="col-md-2">
                <a href="{% url 'airport:detail'  item.airport_id %}" class="btn btn-success">Details</a>
            </div>
        </div>
    {% endfor %}

    <div class="pagination">
        <span class="step-links">
            {% if airport_list.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ airport_list.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ airport_list.number }} of {{ airport_list.paginator.num_pages }}.
            </span>

            {% if airport_list.has_next %}
                <a href="?page={{ airport_list.next_page_number }}">next</a>
                <a href="?page={{ airport_list.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

aviation/airport/templates/airport/asia.html
{% extends 'airport/base.html' %}

{% block body %}
    <h1>List of all airports in Asia</h1>

    <form action="" method="GET">
        <input type="search" name="airport_name">
        <button type="submit">Search</button>
    </form>

    {% for item in airport_list %}
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-4">
                <h4>{{ item.airport_name }}</h3>
                <h6>{{ item.municipality }}</h3>
                <h6>{{ item.country }}</h3>
            </div>
            <div class="col-md-2">
                <a href="{% url 'airport:detail'  item.airport_id %}" class="btn btn-success">Details</a>
            </div>
        </div>
    {% endfor %}

    <div class="pagination">
        <span class="step-links">
            {% if airport_list.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ airport_list.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ airport_list.number }} of {{ airport_list.paginator.num_pages }}.
            </span>

            {% if airport_list.has_next %}
                <a href="?page={{ airport_list.next_page_number }}">next</a>
                <a href="?page={{ airport_list.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

aviation/airport/templates/airport/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'airport/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-primary navbar-dark">
        <a href="#" class="navbar-brand">Airport App</a>

        <!-- Links to add page using URL tag from Django -->
        <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'airport:index' %}">Homepage</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'airport:create_airport' %}">Add airport</a>
            </li>
        </ul>
    </nav>


    <!-- Placeholder for the main content -->
    {% block body %}
    {% endblock %}
</body>
</html>

aviation/airport/templates/airport/detail.html
{% extends 'airport/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4">

        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <h2>Name of the airport: {{ airport.airport_name }}</h2>
            <h4>Type of airport: {{ airport.airport_type }}</h4>
            <h4>Latitude degree: {{ airport.latitude }}</h4>
            <h4>Longitude degree: {{ airport.longitude }}</h4>
            <h4>Elevation in meters: {{ airport.elevation }}</h4>
            <h4>Continent: {{ airport.continent }}</h4>
            <h4>Country: {{ airport.country }}</h4>
            <h4>Municipality: {{ airport.municipality }}</h4>
            <a class="btn btn-primary" href="{% url 'airport:update_airport' airport.airport_id %}">Edit</a>
            <a class="btn btn-secondary" href="{% url 'airport:delete_airport' airport.airport_id %}">Delete</a>
            <a class="btn btn-light" href="{% url 'airport:airport' %}">Cancel</a>
        </div>
    </div>
</div>

{% endblock %}

aviation/airport/templates/airport/index.html
{% extends 'airport/base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
</head>
<body>
    {% block body %}
            
        <h2 style="text-align: center;">Homepage</h2>
        <br>
        <h4 style="text-align: center;">Endpoints</h4>
        <br>
        
        <div style="display: flex;">
        <ul style="list-style-type: none;">
            <!-- Link to a list of all airports -->
            <li><a href="{% url 'airport:airport' %}">List of world airports</a></li>
            <br>
            <li><a href="{% url 'airport:asia' %}">List of airports in Asia</a></li>
            <br>
            <li><a href="{% url 'airport:africa' %}">List of airports in Africa</a></li>
            <br>
            <li><a href="{% url 'airport:oceania' %}">List of airports in Oceania</a></li>
            <br>
            <li><a href="{% url 'airport:southamerica' %}">List of airports in South and Central America</a></li>
            <br>
            <li><a href="{% url 'airport:antartica' %}">List of airports in Antartica</a></li>
            <br>
            <li><a href="{% url 'airport:northamerica' %}">List of airports in North America</a></li>
        </ul>


        <br>

        <ul>
            <li>POST http://localhost:8000/add add a new airport to the list of airports</li>
            <a href="http://localhost:8000/add">http://localhost:8000/add</a>
            
            <li>GET http://localhost:8000/airport/[airport_id]/ returns a selected airport and its description, [airport_id] is a placeholder for the specific ID of the airport</li>
            <a href="http://localhost:8000/airport/3/">http://localhost:8000/airport/3/</a>

            <li>GET http://localhost:8000/airport/ returns a list of all airports</li>
            <a href="http://localhost:8000/airport/">http://localhost:8000/airport/</a>

            <li>UPDATE http://localhost:8000/update/[airport_id]/ updates the information of a selected airport, [airport_id] is a placeholder for the specific ID of the airport</li>
            <a href="http://localhost:8000/update/9/">http://localhost:8000/update/9/</a>

            <li>DELETE http://localhost:8000/delete/[airport_id]/ delete a selected airport from the list, [airport_id] is a placeholder for the specific ID of the airport</li>
            <a href="http://localhost:8000/delete/9/">http://localhost:8000/delete/9/</a>

            <li>API http://localhost:8000/api/</li>
            <a href="http://localhost:8000/api/">http://localhost:8000/api/</a>
        </ul>

        <div style="float: right;">
            {% load static %}
            <img src="{% static 'images/Minnie.jpg' %}" alt="Minnie at the airport" style="width: 80%; height: auto;">
            <p>© Disney. This image is used for educational purposes and is the property of Disney.</p>
        </div>
    </div>
    {% endblock %}

</body>
</html>

aviation/airport/templates/airport/northamerica.html
{% extends 'airport/base.html' %}

{% block body %}
    <h1>List of all airports in North America</h1>

    <form action="" method="GET">
        <input type="search" name="airport_name">
        <button type="submit">Search</button>
    </form>

    {% for item in airport_list %}
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-4">
                <h4>{{ item.airport_name }}</h3>
                <h6>{{ item.municipality }}</h3>
                <h6>{{ item.country }}</h3>
            </div>
            <div class="col-md-2">
                <a href="{% url 'airport:detail'  item.airport_id %}" class="btn btn-success">Details</a>
            </div>
        </div>
    {% endfor %}

    <div class="pagination">
        <span class="step-links">
            {% if airport_list.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ airport_list.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ airport_list.number }} of {{ airport_list.paginator.num_pages }}.
            </span>

            {% if airport_list.has_next %}
                <a href="?page={{ airport_list.next_page_number }}">next</a>
                <a href="?page={{ airport_list.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

aviation/airport/templates/airport/oceania.html
{% extends 'airport/base.html' %}

{% block body %}
    <h1>List of all airports in Oceania</h1>

    <form action="" method="GET">
        <input type="search" name="airport_name">
        <button type="submit">Search</button>
    </form>

    {% for item in airport_list %}
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-4">
                <h4>{{ item.airport_name }}</h3>
                <h6>{{ item.municipality }}</h3>
                <h6>{{ item.country }}</h3>
            </div>
            <div class="col-md-2">
                <a href="{% url 'airport:detail'  item.airport_id %}" class="btn btn-success">Details</a>
            </div>
        </div>
    {% endfor %}

    <div class="pagination">
        <span class="step-links">
            {% if airport_list.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ airport_list.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ airport_list.number }} of {{ airport_list.paginator.num_pages }}.
            </span>

            {% if airport_list.has_next %}
                <a href="?page={{ airport_list.next_page_number }}">next</a>
                <a href="?page={{ airport_list.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

aviation/airport/templates/airport/southamerica.html
{% extends 'airport/base.html' %}

{% block body %}
    <h1>List of all airports in South America</h1>

    <form action="" method="GET">
        <input type="search" name="airport_name">
        <button type="submit">Search</button>
    </form>

    {% for item in airport_list %}
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-4">
                <h4>{{ item.airport_name }}</h3>
                <h6>{{ item.municipality }}</h3>
                <h6>{{ item.country }}</h3>
            </div>
            <div class="col-md-2">
                <a href="{% url 'airport:detail'  item.airport_id %}" class="btn btn-success">Details</a>
            </div>
        </div>
    {% endfor %}

    <div class="pagination">
        <span class="step-links">
            {% if airport_list.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ airport_list.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ airport_list.number }} of {{ airport_list.paginator.num_pages }}.
            </span>

            {% if airport_list.has_next %}
                <a href="?page={{ airport_list.next_page_number }}">next</a>
                <a href="?page={{ airport_list.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock %}